# Generated by Django 5.0.3 on 2024-12-14 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('security_code', models.CharField(blank=True, max_length=50, null=True)),
                ('email_notification', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('inactive', 'Inactive'), ('active', 'Active')], default='trial', max_length=10)),
                ('profile_image', models.ImageField(blank=True, default='profile/default.png', null=True, upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
