# Generated by Django 5.0.3 on 2025-01-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Expense_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
